### ISSUE TITLE
Blackmarket (old)

### ISSUE THREAD

**Issue by W1-PopelierE** [TotomInc/blackmarket-reloaded#42]
Hello,

Can you publish the Blackmarket here?
The non-reloaded version.
Because that one is much cooler.

**Comment by TotomInc** [comment]
Hi,

Indeed, the original blackmarket (so the old version, who is published in Kongregate), can be found in the totominc.github.io repo then in the blackmarket folder.

The reloaded version will probably not see the official release since I'm working on another project and I'm still learning.

However, I thought about doing some updates on the original blackmarket.

**Comment by W1-PopelierE** [comment]
Am I allowed to change it? but ofcourse give you credits?

**Comment by TotomInc** [comment]
Yes, is it to run a local version of the game just for you and testing purposes or is it to contribute for the original repo? You are allowed to change it only for testing purposes, only for you.

If you give me credits about the game, it's OK.

**Comment by W1-PopelierE** [comment]
I want to change the whole game idea, and publish it on a site. (you will get credits at the footer with a link to your profile.)

**Comment by TotomInc** [comment]
That's OK, there is no problems.
